# Generated by Django 6.0.5 on 2026-05-12 12:06

import aws_shared.languages
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supertype', models.CharField(choices=[('pokemon', 'Pokemon'), ('trainer', 'Trainer'), ('energy', 'Energy')], default='pokemon', max_length=20)),
                ('subtype', models.CharField(blank=True, choices=[('basic', 'Basic'), ('stage-1', 'Stage 1'), ('stage-2', 'Stage 2'), ('trainer', 'Trainer'), ('stadium', 'Stadium'), ('special', 'Special')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('retreat_cost', models.IntegerField(default=0)),
                ('weak_value', models.CharField(blank=True, help_text='e.g. x2, +20', max_length=10)),
                ('resist_value', models.CharField(blank=True, help_text='e.g. -20', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CardVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('color_code', models.CharField(blank=True, max_length=7)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='energies/icons')),
            ],
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.CharField(blank=True, max_length=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='catalog.card')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='catalog.card')),
            ],
            options={
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='CardPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=50)),
                ('master_image', models.ImageField(blank=True, null=True, upload_to='cards/master/')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printings', to='catalog.card')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printings', to='catalog.cardvariant')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='resist_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards_with_resistance', to='catalog.energytype'),
        ),
        migrations.AddField(
            model_name='card',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='cards', to='catalog.energytype'),
        ),
        migrations.AddField(
            model_name='card',
            name='weak_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards_with_weakness', to='catalog.energytype'),
        ),
        migrations.CreateModel(
            name='AttackCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='catalog.attack')),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.energytype')),
            ],
            options={
                'unique_together': {('attack', 'energy_type')},
            },
        ),
        migrations.AddField(
            model_name='attack',
            name='cost_types',
            field=models.ManyToManyField(related_name='attacks', through='catalog.AttackCost', to='catalog.energytype'),
        ),
        migrations.AddField(
            model_name='card',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='catalog.expansion'),
        ),
        migrations.CreateModel(
            name='LocalizedAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('jp', 'Japanese')], max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='catalog.ability')),
            ],
            options={
                'verbose_name_plural': 'LocalizedAbilities',
                'unique_together': {('ability', 'language')},
            },
        ),
        migrations.CreateModel(
            name='LocalizedAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('jp', 'Japanese')], max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='catalog.attack')),
            ],
            options={
                'unique_together': {('attack', 'language')},
            },
        ),
        migrations.CreateModel(
            name='LocalizedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('jp', 'Japanese')], default=aws_shared.languages.SupportedLanguage['EN'], max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='catalog.card')),
            ],
            options={
                'unique_together': {('card', 'language')},
            },
        ),
        migrations.CreateModel(
            name='LocalizedEnergyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('jp', 'Japanese')], max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='catalog.energytype')),
            ],
            options={
                'unique_together': {('energy_type', 'language')},
            },
        ),
        migrations.CreateModel(
            name='LocalizedExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('jp', 'Japanese')], max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='catalog.expansion')),
            ],
            options={
                'unique_together': {('expansion', 'language')},
            },
        ),
    ]
