# Generated by Django 6.0.5 on 2026-05-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizedcard',
            name='total_cards_override',
            field=models.IntegerField(blank=True, help_text='Specific total for a group (e.g. 32 for Aquapolis Holos)', null=True),
        ),
        migrations.AddField(
            model_name='localizedexpansion',
            name='total_cards',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localizedcard',
            name='number',
            field=models.CharField(help_text="e.g. 'H28', '40'", max_length=10),
        ),
    ]
