# Generated by Django 6.0.5 on 2026-05-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_localizedcard_total_cards_override_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localizedcard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='localizedcard',
            name='printing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='catalog.cardprinting'),
        ),
        migrations.RemoveField(
            model_name='localizedcard',
            name='card',
        ),
    ]
