# Generated by Django 6.0.5 on 2026-05-12 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_localizedcard_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizedcard',
            name='printing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='catalog.cardprinting'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='localizedcard',
            unique_together={('printing', 'language')},
        ),
    ]
