# Generated by Django 6.0.5 on 2026-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_localizedcard_printing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
