# Generated by Django 6.0.5 on 2026-05-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_energytype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='subtype',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('stage-1', 'Stage 1'), ('stage-2', 'Stage 2'), ('item', 'Item'), ('supporter', 'Supporter'), ('stadium', 'Stadium'), ('special', 'Special')], max_length=20),
        ),
    ]
