# Generated by Django 6.0.5 on 2026-05-13 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_card_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='expansion',
        ),
        migrations.AddField(
            model_name='card',
            name='internal_name',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardprinting',
            name='expansion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='catalog.expansion'),
            preserve_default=False,
        ),
    ]
