# Generated by Django 6.0.5 on 2026-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_card_expansion_card_internal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='energy_value',
            field=models.PositiveIntegerField(blank=True, help_text='Face value of the energy type', null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtype',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('stage-1', 'Stage 1'), ('stage-2', 'Stage 2'), ('basic-energy', 'Basic Energy'), ('special-energy', 'Special Energy'), ('item', 'Item'), ('supporter', 'Supporter'), ('stadium', 'Stadium'), ('special', 'Special')], max_length=20),
        ),
    ]
