# Generated by Django 6.0.5 on 2026-05-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_card_energy_value_alter_card_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardprinting',
            name='master_image',
        ),
        migrations.AddField(
            model_name='localizedcard',
            name='master_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='localizedcard',
            name='raw_image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/raw/'),
        ),
    ]
