# Generated by Django 6.0.5 on 2026-05-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_cardprinting_master_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizedcard',
            name='image_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='pending', max_length=20),
        ),
    ]
