# Generated by Django 6.0.5 on 2026-05-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_localizedcard_image_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizedcard',
            name='image_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
